my_string = input("Введите строку: ")
print(f'Длинна введенной строки: {len(my_string)}')
print(f'Строка в верхнем регистре: {my_string.upper()}')
print(f'Строка в нижнем регистре: {my_string.lower()}')
print(f'Строка без пробелов: {my_string.replace(" ", "")}')
print(f'Первый символ строки: {my_string[0]}')
print(f'Последний символ строки: {my_string[-1]}')
